### ISSUE TITLE
When making a couple of bookings for the same PT, availability checks start to fail

### ISSUE THREAD

**Issue by mike-hogan** [cozemble/breezbook#37]
Getting availability for location breezbook-gym_dev_europe.uk.harlow, tenant breezbook-gym and service breezbook-gym_dev_pt.service.1hr from 2024-06-21 to 2024-06-28 in environment dev
file:///Users/mikehogan/repos/personal/cozemble/breezbook/backend/airtable/dist/esm/core/getAvailabilityForService.js:47
        throw new Error(firstError.errorMessage);
              ^

Error: No suitable resource found for requirement
    at getAvailableSlots (file:///Users/mikehogan/repos/personal/cozemble/breezbook/backend/airtable/dist/esm/core/getAvailabilityForService.js:47:15)
    at getAvailabilityForService2 (file:///Users/mikehogan/repos/personal/cozemble/breezbook/backend/airtable/dist/esm/core/getAvailabilityForService.js:33:26)
    at getServiceAvailabilityForLocation (file:///Users/mikehogan/repos/personal/cozemble/breezbook/backend/airtable/dist/esm/express/availability/getServiceAvailabilityForLocation.js:70:64)
    at async expressBridge (file:///Users/mikehogan/repos/personal/cozemble/breezbook/backend/airtable/dist/esm/infra/endpoint.js:123:22)
    at async onGetServiceAvailabilityForLocationExpress (file:///Users/mikehogan/repos/personal/cozemble/breezbook/backend/airtable/dist/esm/express/availability/getServiceAvailabilityForLocation.js:43:5)

Node.js v18.16.0
[nodemon] app crashed - waiting for file changes before starting...

**Comment by mike-hogan** [comment]
fixed
